resources:
- name: concourse
  type: git
  source:
    uri: git@github.com:concourse/concourse-bosh-release.git
    branch: release/4.2.x
    private_key: ((concourse_repo_private_key))

- name: concourse-bosh-release
  type: git
  source:
    uri: git@github.com:concourse/concourse-bosh-release.git
    branch: master
    private_key: ((concourse_repo_private_key))

- name: github-bosh-release
  type: github-release
  source:
    owner: concourse
    repository: concourse-bosh-release
    access_token: ((concourse_github_release.access_token))

- name: version
  type: semver
  source:
    bucket: concourse-semver-resource-versions
    driver: gcs
    initial_version: 4.2.4-rc.1
    json_key: ((gcs_version_bucket_key))
    key: hotfix-4.2.x

- name: final-release
  type: s3
  source:
    bucket: concourse-releases
    regexp: concourse-(.*).tgz
    access_key_id: ((concourse_release_bucket.access_key))
    secret_access_key: ((concourse_release_bucket.secret_key))

- name: garden-runc
  type: bosh-io-release
  source:
    repository: cloudfoundry/garden-runc-release

- name: postgres-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/postgres-release

- name: gcp-xenial-stemcell
  type: pivnet
  source:
    api_token: ((concourse_pivnet_token))
    product_slug: stemcells-ubuntu-xenial
    sort_by: semver

- name: concourse-boshio
  type: bosh-io-release
  source:
    repository: concourse/concourse-bosh-release
    regexp: 4.2.*

- name: concourse-bosh-deployment-latest
  type: git
  source:
    uri: git@github.com:concourse/concourse-bosh-deployment.git
    branch: release/4.2.x
    private_key: ((concourse_repo_private_key))

- name: concourse-bosh-deployment-released
  type: git
  source:
    uri: git@github.com:concourse/concourse-bosh-deployment.git
    branch: release/4.2.x
    private_key: ((concourse_repo_private_key))

- name: fly-rc
  type: gcs
  source:
    bucket: fly-artifacts
    json_key: ((concourse_artifacts_json_key))
    regexp: rcs/fly-(.*).tgz

- name: bosh-rc
  type: s3
  source:
    bucket: concourse-release-candidates
    regexp: concourse-(.*).tgz
    access_key_id: ((concourse_release_bucket.access_key))
    secret_access_key: ((concourse_release_bucket.secret_key))

- name: upgrade-deployment
  type: bosh-deployment
  source:
    target: ((bosh_target))
    deployment: concourse-test-upgrade-4-2-x
    client: ((bosh_client.id))
    client_secret: ((bosh_client.secret))

- name: wats-deployment
  type: bosh-deployment
  source:
    target: ((bosh_target))
    deployment: concourse-wats-4-2-x
    client: ((bosh_client.id))
    client_secret: ((bosh_client.secret))

- name: daily-timer
  type: time
  source:
    interval: 1h
    location: America/Toronto
    start: 2:00 AM
    stop: 3:00 AM
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]

jobs:
- name: fly
  public: true
  plan:
  - get: concourse
  - get: version
    trigger: true
  - aggregate:
    - task: linux
      file: concourse/ci/fly-linux.yml
    - task: darwin
      file: concourse/ci/fly-darwin.yml
    - task: windows
      file: concourse/ci/fly-windows.yml

- name: go-concourse
  public: true
  plan:
  - get: concourse
  - get: version
    trigger: true
  - task: go-unit
    file: concourse/ci/go-concourse.yml

- name: worker
  public: true
  plan:
  - get: concourse
  - get: version
    trigger: true
  - task: go-unit
    file: concourse/ci/worker.yml

- name: atc
  public: true
  serial: true
  plan:
  - get: concourse
  - get: version
    trigger: true
  - task: go-unit
    file: concourse/ci/atc-go.yml
    privileged: true

- name: baggageclaim
  public: true
  serial: true
  plan:
  - get: concourse
  - get: version
    trigger: true
  - task: build
    privileged: true
    file: concourse/ci/baggageclaim.yml

- name: skymarshal
  public: true
  serial: true
  plan:
  - get: concourse
  - get: version
    trigger: true
  - task: build
    file: concourse/ci/skymarshal.yml

- name: web
  public: true
  serial: true
  plan:
  - get: concourse
  - get: version
    trigger: true
  - aggregate:
    - task: build
      file: concourse/ci/web.yml
    - task: elm-unit
      file: concourse/ci/atc-elm.yml

- name: tsa
  public: true
  plan:
  - get: concourse
  - get: version
    trigger: true
  - task: build
    file: concourse/ci/tsa.yml

- name: promote-rc
  public: true
  plan:
  - get: version
  - put: version
    params:
      bump: final

- name: bump-patch
  public: true
  plan:
  - get: version
  - put: version
    params:
      bump: patch
      pre: rc

- name: bump-rc
  public: true
  plan:
  - get: concourse
    trigger: true
  - get: version
  - get: garden-runc
    trigger: true
  - get: daily-timer
    trigger: true
  - put: version
    params:
      pre: rc

- name: fly-rc
  public: true
  plan:
  - get: concourse
    passed: [atc, fly, go-concourse, tsa, baggageclaim, skymarshal, web, worker]
  - get: final-version
    resource: version
    passed: [atc, fly, go-concourse, tsa, baggageclaim, skymarshal, web, worker]
    trigger: true
  - get: garden-runc
    passed: [bump-rc]
  - aggregate:
    - task: build-linux
      file: concourse/ci/fly-build-linux.yml
    - task: build-darwin
      file: concourse/ci/fly-build-darwin.yml
    - task: build-windows
      file: concourse/ci/fly-build-windows.yml
  - task: build-release
    file: concourse/ci/fly-build-release.yml
    input_mapping:
      version: final-version
  - put: fly-rc
    params:
      file: release/fly*.tgz

- name: bosh-rc
  public: true
  plan:
  - aggregate:
    - get: concourse
      trigger: true
      passed: [fly-rc]
    - get: garden-runc
      trigger: true
      passed: [fly-rc]
    - get: version
      trigger: true
      passed: [fly-rc]
    - get: final-version
      trigger: true
      resource: version
      passed: [fly-rc]
    - get: fly-rc
      trigger: true
      passed: [fly-rc]
    - get: postgres-release
      trigger: true
    - get: gcp-xenial-stemcell
      trigger: true
      params:
        globs: []
    - get: concourse-bosh-deployment-latest
      trigger: true
  - task: fly-unpack-release
    file: concourse/ci/fly-unpack-release.yml
  - task: create-bosh-rc
    file: concourse/ci/create-bosh-rc.yml
    input_mapping:
      fly-rc: fly-rc-unpacked
  - put: bosh-rc
    params: {file: bosh-rc/concourse-*.tgz}

- name: bosh-upgrade
  serial: true
  plan:
  - aggregate:
    - get: concourse
      trigger: true
      passed: [bosh-rc]
    - get: bosh-rc
      trigger: true
      passed: [bosh-rc]
    - get: version
      trigger: true
      passed: [bosh-rc]
    - get: garden-runc
      trigger: true
      passed: [bosh-rc]
    - get: fly-rc
      trigger: true
      passed: [bosh-rc]
    - get: postgres-release
      trigger: true
      passed: [bosh-rc]
    - get: gcp-xenial-stemcell
      trigger: true
      passed: [bosh-rc]
      params:
        globs: [light-bosh-stemcell-*-google-kvm-ubuntu-xenial-go_agent.tgz]
    - get: concourse-bosh-deployment-latest
      trigger: true
      passed: [bosh-rc]
    - get: final-release
    - get: concourse-bosh-deployment-released
  - put: delete-upgrade-deployment
    resource: upgrade-deployment
    params:
      manifest: concourse-bosh-deployment-latest/cluster/concourse.yml
      delete:
        enabled: true
        force: true
  - put: final-release-deployment
    resource: upgrade-deployment
    params:
      manifest: concourse-bosh-deployment-released/cluster/concourse.yml
      stemcells: [gcp-xenial-stemcell/*.tgz]
      releases:
      - garden-runc/*.tgz
      - postgres-release/*.tgz
      - final-release/concourse-*.tgz
      ops_files:
      - concourse-bosh-deployment-released/cluster/operations/dev-versions.yml
      - concourse-bosh-deployment-released/cluster/operations/default-test-user.yml
      vars:
        db_persistent_disk_type: small
        db_vm_type: test
        deployment_name: concourse-test-upgrade-4-2-x
        external_url: ~
        network_name: test
        web_vm_type: test
        worker_vm_type: test
  - task: discover-bosh-endpoint-info
    file: concourse/ci/discover-bosh-endpoint-info.yml
    params:
      BOSH_ENVIRONMENT: ((bosh_target))
      BOSH_CLIENT: ((bosh_client.id))
      BOSH_CLIENT_SECRET: ((bosh_client.secret))
      BOSH_DEPLOYMENT: concourse-test-upgrade-4-2-x
      BOSH_INSTANCE_GROUP: web
  - task: fly-unpack-release
    file: concourse/ci/fly-unpack-release.yml
  - task: create-test-pipeline
    file: concourse/ci/create-uber-pipeline.yml
    input_mapping:
      fly-rc: fly-rc-unpacked
    params:
      WEB_USERNAME: "test"
      WEB_PASSWORD: "test"
      PIPELINE_NAME: test-pipeline
  - put: bosh-rc-deployment
    resource: upgrade-deployment
    params:
      manifest: concourse-bosh-deployment-latest/cluster/concourse.yml
      stemcells: [gcp-xenial-stemcell/*.tgz]
      releases:
      - garden-runc/*.tgz
      - postgres-release/*.tgz
      - bosh-rc/concourse-*.tgz
      ops_files:
      - concourse-bosh-deployment-latest/cluster/operations/dev-versions.yml
      - concourse-bosh-deployment-latest/cluster/operations/default-test-user.yml
      vars:
        db_persistent_disk_type: small
        db_vm_type: test
        deployment_name: concourse-test-upgrade-4-2-x
        external_url: ~
        network_name: test
        web_vm_type: test
        worker_vm_type: test
  - task: verify-test-pipeline
    file: concourse/ci/verify-uber-pipeline.yml
    input_mapping:
      fly-rc: fly-rc-unpacked
    params:
      WEB_USERNAME: "test"
      WEB_PASSWORD: "test"
      PIPELINE_NAME: test-pipeline
  - task: testflight
    file: concourse/ci/testflight.yml
    params:
      ATC_USERNAME: "test"
      ATC_PASSWORD: "test"
    timeout: 1h

- name: bosh-watsjs
  public: true
  plan:
  - aggregate:
    - get: concourse
      passed: [bosh-rc]
      trigger: true
    - get: bosh-rc
      passed: [bosh-rc]
      trigger: true
    - get: version
      passed: [bosh-rc]
      trigger: true
    - get: garden-runc
      passed: [bosh-rc]
      trigger: true
    - get: fly-rc
      passed: [bosh-rc]
      trigger: true
    - get: postgres-release
      passed: [bosh-rc]
      trigger: true
    - get: gcp-xenial-stemcell
      passed: [bosh-rc]
      trigger: true
      params:
        globs: [light-bosh-stemcell-*-google-kvm-ubuntu-xenial-go_agent.tgz]
    - get: concourse-bosh-deployment
      resource: concourse-bosh-deployment-latest
      passed: [bosh-rc]
      trigger: true
  - put: wats-deployment
    params:
      manifest: concourse-bosh-deployment/cluster/concourse.yml
      stemcells: [gcp-xenial-stemcell/*.tgz]
      releases:
      - garden-runc/*.tgz
      - postgres-release/*.tgz
      - bosh-rc/concourse-*.tgz
      ops_files:
      - concourse-bosh-deployment/cluster/operations/dev-versions.yml
      - concourse-bosh-deployment/cluster/operations/add-local-users.yml
      vars:
        db_persistent_disk_type: small
        db_vm_type: test
        deployment_name: concourse-wats-4-2-x
        external_url: ~
        network_name: test
        web_vm_type: test
        worker_vm_type: test
        main_team_local_users:
        - test
        add_local_users:
        - 'test:$2a$10$iEnPPyINsvif.wytAMgf7.HcForfasqXbbHyNsR5knEcRhjuR4MEW'
        - 'test2:$2a$10$w9ijd0MV6b3LjPlRNlZN/.dYan8aITbJU9Wb1fH0Z8.qgqnEGHEmq'
  - task: discover-bosh-endpoint-info
    file: concourse/ci/discover-bosh-endpoint-info.yml
    params:
      BOSH_ENVIRONMENT: ((bosh_target))
      BOSH_CLIENT: ((bosh_client.id))
      BOSH_CLIENT_SECRET: ((bosh_client.secret))
      BOSH_DEPLOYMENT: concourse-wats-4-2-x
      BOSH_INSTANCE_GROUP: web
  - task: wats
    file: concourse/ci/wats.yml
    timeout: 1h
  - task: fly-unpack-release
    file: concourse/ci/fly-unpack-release.yml
  - task: watsjs
    file: concourse/ci/watsjs.yml
    input_mapping:
      fly-rc: fly-rc-unpacked
    params:
      ATC_USERNAME: "test"
      ATC_PASSWORD: "test"
    timeout: 1h

- name: shipit
  serial: true
  plan:
  - aggregate:
    - get: concourse
      passed: [bosh-upgrade, bosh-watsjs]
    - get: concourse-bosh-release
    - get: version
      passed: [bosh-upgrade, bosh-watsjs]
    - get: garden-runc-release
      resource: garden-runc
      passed: [bosh-upgrade, bosh-watsjs]
    - get: postgres-release
      passed: [bosh-upgrade, bosh-watsjs]
    - get: bosh-rc
      passed: [bosh-upgrade, bosh-watsjs]
    - get: concourse-bosh-deployment-latest
      passed: [bosh-upgrade, bosh-watsjs]
    - get: gcp-xenial-stemcell
      params:
        globs: []
      passed: [bosh-upgrade, bosh-watsjs]
    - get: fly-rc
      passed: [bosh-upgrade, bosh-watsjs]
  - task: finalize-release
    file: concourse/ci/finalize-release.yml
    params: {GCP_JSON_KEY: ((concourse_artifacts_json_key))}
  - aggregate:
    - put: concourse-bosh-release
      params:
        repository: final-release-repo
        merge: true
    - put: final-release
      params: {file: final-release-tarball/concourse-*.tgz}

  # concouse/concourse-bosh-release
- name: bosh-github-release
  serial: true
  plan:
  - aggregate:
    - get: final-release
      passed: [shipit]
    - get: garden-runc
      passed: [shipit]
    - get: concourse
      params: {submodules: none}
      passed: [shipit]
    - get: version
      passed: [shipit]
    - get: gcp-xenial-stemcell
      passed: [shipit]
      params:
        globs: []
    - get: concourse-bosh-deployment-latest
    - get: postgres-release
  - aggregate:
    - task: build-release-notes
      file: concourse/ci/build-release-notes.yml
  - put: github-bosh-release
    params:
      name: release-notes/release-name
      tag: release-notes/release-name
      commitish: concourse/.git/ref

- name: bump-concourse-bosh-deployment-released
  serial: true
  plan:
  - aggregate:
    - get: concourse-bosh-deployment-latest
    - get: concourse-boshio
      trigger: true
    - get: garden-runc
      passed:
      - shipit
    - get: postgres-release
      passed:
      - shipit
  - task: bump-versions
    file: concourse-bosh-deployment-latest/ci/bump-versions.yml
    input_mapping:
      concourse-bosh-deployment: concourse-bosh-deployment-latest
  - aggregate:
    - put: concourse-bosh-deployment-released
      params:
        merge: true
        repository: bumped-repo

resource_types:
- name: git
  type: registry-image
  source:
    repository: concourse/git-resource
    tag: 1.3.0

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
- name: bosh-io-release
  type: registry-image
  source: {repository: concourse/bosh-io-release-resource}

- name: github-release
  type: registry-image
  source: {repository: concourse/github-release-resource}

- name: s3
  type: registry-image
  source: {repository: concourse/s3-resource}

- name: bosh-io-stemcell
  type: registry-image
  source: {repository: concourse/bosh-io-stemcell-resource}

- name: docker-image
  type: registry-image
  privileged: true
  source: {repository: concourse/docker-image-resource}

- name: bosh-deployment
  type: registry-image
  source: {repository: cloudfoundry/bosh-deployment-resource}

- name: gcs
  type: registry-image
  source: {repository: frodenas/gcs-resource}
